#! /bin/sh

sxhkd &
dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a qutebrowser desktop='^1' follow=on focus=on
bspc rule -a firefoxdeveloperedition desktop='^1' follow=on focus=on
bspc rule -a Zathura state=tiled
bspc rule -a Steam desktop='^10'
xwallpaper --zoom $HOME/Pictures/Wallpapers/config_wallpaper_futuristiccity.jpg &
wal -R &
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true
/home/god/.config/polybar/launch.sh
picom --config $HOME/.config/picom/picom.conf &
pgrep bspswallow || bspswallow &
setxkbmap -layout "us,latam" -option "grp:win_space_toggle"
xset r rate 300 70
