#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xwallpaper --zoom $HOME/Pictures/Wallpapers/cyberpunk.jpg &
#feh --bg-fill $HOME/Pictures/Wallpapers/cyberpunk.jpg &
wal -R &
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true
bspc config border_width 2
bspc config window_gap 25
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a Steam desktop='^0'
polybar example &
picom --config $HOME/.config/picom/picom.conf &
setxkbmap -layout "us,latam" -option "grp:win_space_toggle"
